/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/log.h>
/* Header for class com_bihe0832_md5_MD5 */

#ifndef _Included_com_bihe0832_md5_MD5
#define _Included_com_bihe0832_md5_MD5
#ifdef __cplusplus
extern "C" {
#endif
#undef com_bihe0832_md5_MD5_VERSION
#define com_bihe0832_md5_MD5_VERSION 1L

#define LOGD(fmt, ...)   __android_log_print(ANDROID_LOG_DEBUG, "YSDK  cpp", fmt, __VA_ARGS__)

/*
 * Class:     com_bihe0832_md5_MD5
 * Method:    getMD5Result
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_bihe0832_md5_MD5_getMD5Result
  (JNIEnv *, jclass, jstring);

JNIEXPORT jint JNICALL Java_com_bihe0832_md5_MD5_getVersion
(JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
